// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzcseetasbisnpnmwsiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y3NlZXRhc2Jpc25wbm13c2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzE2NzMsImV4cCI6MjA2NDAwNzY3M30.CXrBaWNaq5kqBiaQavTITAKOKsoBzGJH0YayLvktB34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);